import type { Product } from "services/service-types";
import type { CartItem } from "store/cart-store";

export const PRODUCTS: Product[] = [
  {
    id: 3289,
    name: "vCluster",
    descriptionSale:
      "vClusters only incur usage costs from the resources you consume",
    displayName: "vCluster",
    type: "service",
    currencyId: [5, "CHF"],
    listPrice: 0,
    active: true,
    categId: [111, "All / Nine Kubernetes Engine / Services"],
    shIsBundle: false,
    shBundleProductIds: [],
    categPath: ["All", "Nine Kubernetes Engine", "Services"],
  },
  {
    id: 3032,
    name: "Cloudserver C1",
    descriptionSale: "1GiB RAM, 1 vCPU",
    displayName: "Cloudserver C1",
    type: "service",
    currencyId: [5, "CHF"],
    listPrice: 11,
    active: true,
    categId: [17, "All / Cloudserver"],
    shIsBundle: false,
    shBundleProductIds: [],
    categPath: ["All", "Cloudserver"],
  },
  {
    id: 3033,
    name: "Cloudserver C2",
    descriptionSale: "2GiB RAM, 1 vCPU",
    displayName: "Cloudserver C2",
    type: "service",
    currencyId: [5, "CHF"],
    listPrice: 22,
    active: true,
    categId: [17, "All / Cloudserver"],
    shIsBundle: false,
    shBundleProductIds: [],
    categPath: ["All", "Cloudserver"],
  },
  {
    active: true,
    categId: [111, "All / Nine Kubernetes Engine / Services"],
    categPath: ["All", "Nine Kubernetes Engine", "Services"],
    currencyId: [5, "CHF"],
    descriptionSale:
      "vClusters only incur usage costs from the resources you consume",
    displayName: "vCluster",
    id: 3289,
    listPrice: 0,
    name: "vCluster",
    shBundleProductIds: [],
    shIsBundle: false,
    type: "service",
  },
];

export const CART_ITEMS: CartItem[] = [
  {
    product: {
      id: 1,
      active: true,
      bundleProducts: [],
      categId: [17, "All / Cloudserver"],
      categPath: ["All", "Cloudserver"],
      currencyId: [1, "CHF"],
      descriptionSale: "Description 1",
      displayName: "Product 1",
      listPrice: 100,
      name: "Product 1",
      shBundleProductIds: [],
      shIsBundle: false,
      type: "service",
    },
    quantity: 1,
  },
  {
    product: {
      id: 2,
      active: true,
      bundleProducts: [],
      categId: [17, "All / Cloudserver"],
      categPath: ["All", "Cloudserver"],
      currencyId: [1, "CHF"],
      descriptionSale: "Description 2",
      displayName: "Product 2",
      helpText: "Description 2",
      listPrice: 200,
      name: "Product 1",
      shBundleProductIds: [],
      shIsBundle: false,
      type: "service",
    },
    quantity: 2,
  },
];
